### ISSUE TITLE
关于market-draft-recognize.dll，麻烦问下，多谢

### ISSUE THREAD

**Issue by rurusgit** [zhengxinshipiao/zhengxinshipiao-electron#1]
market-draft-recognize.dll
二次开发的话，这个文件可以拿来直接用吗？
这个文件提供的方法是纯本地的吗？就是说断网可以用吗？它内部有没有又调用了接口呢，多谢。

**Comment by zhengxin114** [comment]
二次开发dll可以直接拿来用，但不一定满足您的需求哦。
dll提供的方法是本地调用的，断网是可以调用的，但当前该dll是用来抓取部分网页信息的，有可能涉及到调用网页上的接口。
