### ISSUE TITLE
工程跑起来以后，有两个问题，请问下，多谢：）

### ISSUE THREAD

**Issue by rurusgit** [zhengxinshipiao/zhengxinshipiao-electron#2]
**1. 开发环境下，启动是弹窗报错如下，能都帮忙看下原因，多谢：**
![Image 1](https://user-images.githubusercontent.com/24243075/124242245-1d92ee80-db4f-11eb-9d40-53dd4e5e2f70.png)

**2. 接口地址貌似不太对，哪里修改呢，多谢：**
![Image 2](https://user-images.githubusercontent.com/24243075/124242550-6ea2e280-db4f-11eb-8b04-713b80293b7e.png)

**Comment by zhengxin114** [comment]
从报错来看猜测你的node环境有问题，建议你重装环境以及建议node.js版本不低于12.0.0
